export const portfolioItems = [
    {
      id: 1,
      slug: "club-mall",
      title: "Club Mall",
      client: "Tankbuilder Ireland",
      duration: "2 Weeks",
      link: "https://clubmall.com/home",
      description: "Club Mall is an iconic shopping and leisure destination designed to deliver a premium digital experience for visitors, shoppers, and retailers. The website blends modern UI with interactive technologies to showcase stores, events, and navigation in a seamless way. The platform acts as a digital extension of the physical mall, enhancing visitor engagement and discovery.",
      techStack: ["React.js", "Tailwind CSS", "Node.js", "Interactive Maps API", "CMS Integration"],
      features: ["Event updates & promotional banners", "Interactive store directory", "Dynamic mall navigation map", "Online store & brand integrations", "Mobile-first responsive design"],
      impact: ["Improved visitor engagement and discovery", "Increased footfall through event promotions", "Enhanced brand visibility for retailers", "Seamless digital experience for shoppers"],
      img: "/media/portfolio-banners/club-mall.png",
      tags: ["Web", "React.js", "UI/UX Design"]
    },
    {
      id: 2,
      slug: "free-fuse",
      title: "FreeFuse",
      client: "Sofia Lopez, Director of Technology, NovaCore",
      duration: "1 Week",
      link: "https://freefuse.com/",
      description: "FreeFuse is a collaborative digital platform built to empower individuals and teams to connect, share ideas, and collaborate in real time. The platform focuses on community-driven engagement, intuitive workflows, and scalable architecture to support growing user bases.",
      techStack: ["React.js", "Tailwind CSS", "Node.js", "WebSockets (Real-time features)", "Cloud Hosting"],
      features: ["Real-time collaboration tools", "Project & idea-sharing modules", "Community interaction system", "Secure user authentication", "Scalable, intuitive UI"],
      impact: ["Fostered creative collaboration", "Increased user engagement & retention", "Streamlined idea-sharing workflows", "Built a scalable community platform"],
      img: "/media/portfolio-banners/free-fuse.png",
      tags: ["Web", "React.js"]
    },
    {
      id: 3,
      slug: "maison-heera",
      title: "Maison Heera",
      client: "Daniel Murphy, CTO, TechBridge, USA",
      duration: "2 Weeks",
      link: "https://www.brijeshghevaria.com/",
      description: "Maison Heera is a luxury jewelry brand website crafted to reflect elegance, heritage, and trust. The platform showcases premium collections with high-end visuals and a refined user experience, ensuring seamless browsing and secure online purchases.",
      techStack: ["React.js", "Tailwind CSS", "Node.js", "Secure Payment Gateway", "CMS"],
      features: ["Luxury product showcase", "High-end responsive UI", "Secure online purchasing", "Brand storytelling & heritage pages", "Performance optimization"],
      impact: ["Elevated luxury brand presence", "Increased online jewelry sales", "Improved customer trust", "Smooth cross-device experience"],
      img: "/media/portfolio-banners/maison-heera.png",
      tags: ["Web", "E-commerce", "UI/UX Design"]
    },
    {
      id: 4,
      slug: "asvab-tutoring",
      title: "ASVAB Tutoring",
      client: "Robert Allen, CEO Horizone Soft Solution, US",
      duration: "2 Weeks",
      link: "https://asvab-tutoring.com/",
      description: "ASVAB Tutoring is a comprehensive e-learning platform designed to help students prepare effectively for the ASVAB exam. The platform combines structured learning modules, assessments, and analytics to deliver personalized learning paths.",
      techStack: ["React.js", "Tailwind CSS", "Node.js", "Learning Management System (LMS)", "Analytics Dashboard"],
      features: ["Structured study modules", "Practice tests & assessments", "Personalized learning paths", "Progress tracking dashboard", "Mobile-friendly UI"],
      impact: ["Improved student scores", "Higher learner engagement", "Scalable tutoring infrastructure", "Simplified exam preparation"],
      img: "/media/portfolio-banners/asvab.png",
      tags: ["Web", "Education"]
    },
    // {
    //   id: 5,
    //   title: "Marro App",
    //   client: "David Kim, CEO New Jersey, USA",
    //   duration: "1 Week",
    //   link: "#",
    //   description: "Marro is a productivity-focused mobile application designed to help users manage tasks, goals, and habits efficiently. The app emphasizes simplicity, real-time synchronization, and smart reminders to improve daily productivity.",
    //   techStack: ["React Native", "Node.js", "Firebase", "Push Notification Services"],
    //   features: ["Task & goal management", "Time tracking tools", "Habit monitoring", "Smart reminders & alerts", "Cross-device synchronization"],
    //   impact: ["Increased user productivity", "Better time-management habits", "Improved daily organization", "Enhanced consistency & focus"],
    //   img: "",
    //   tags: ["Mobile", "React Native", "Productivity"]
    // },
    {
      id: 6,
      slug: "norwell",
      title: "Norwell",
      client: "Richard Weight, Project Manager at BearIT srl, Pescara",
      duration: "1 Week",
      link: "https://www.norwell.dk/",
      description: "Norwell is a marine equipment platform built for professionals and enthusiasts. It provides detailed product listings, advanced search capabilities, and expert documentation to simplify marine equipment discovery and purchasing.",
      techStack: ["React.js", "Tailwind CSS", "Node.js", "Product Search Engine", "CMS"],
      features: ["Detailed marine product listings", "Advanced search & filtering", "Dealer locator system", "Expert documentation", "Professional-focused UX"],
      impact: ["Improved product discoverability", "Stronger dealer-customer connections", "Increased trust in product quality", "Enhanced purchasing experience"],
      img: "/media/portfolio-banners/norwell.png",
      tags: ["Web", "Commercial"]
    },
    {
      id: 7,
      slug: "you-skilled-home",
      title: "You Skilled Home",
      client: "John Carter, CTO at Tech Genius Inc, USA",
      duration: "2 Weeks",
      link: "#",
      description: "You Skilled Home is Dubai’s premium fitness platform designed to manage memberships, schedules, and fitness progress digitally. The platform improves gym operations while delivering a personalized experience to members.",
      techStack: ["React.js", "Tailwind CSS", "Node.js", "Booking & Scheduling APIs", "Payment Gateway"],
      features: ["Membership management", "Class scheduling & booking", "Personalized dashboards", "Fitness progress tracking", "Integrated e-commerce"],
      impact: ["Streamlined gym operations", "Increased member engagement", "Improved retention & loyalty", "Fully digitized fitness management"],
      img: "/media/portfolio-banners/you-skilled-home.png",
      tags: ["Web", "Fitness", "Management"]
    },
    {
      id: 8,
      slug: "sanghvi-and-sons",
      title: "Sanghvi & Sons",
      client: "Olivia Martinez, CTO New Jersey, USA",
      duration: "2 Weeks",
      link: "https://sanghvisons.com/",
      description: "Sanghvi & Sons is a premium jewelry e-commerce platform designed to deliver a secure and elegant shopping experience. It showcases extensive collections with customization and order tracking features.",
      techStack: ["React.js", "Tailwind CSS", "Node.js", "Secure E-commerce System", "Payment Gateway"],
      features: ["Extensive jewelry catalog", "Secure checkout", "Jewelry customization", "Order tracking", "Customer support integration"],
      impact: ["Expanded online sales", "Enhanced customer trust", "Improved brand accessibility", "Premium shopping experience"],
      img: "/media/portfolio-banners/sanghvi-and-sons.png",
      tags: ["Web", "E-commerce"]
    },
    {
      id: 9,
      slug: "bjerring-online",
      title: "BJERRING ONLINE",
      client: "Kevin Wong, Director of Dynamo Info Technologies LLC, USA",
      duration: "1 Week",
      link: "#",
      description: "BJERRING ONLINE is a B2B e-commerce platform for industrial equipment and tools, designed to simplify procurement and strengthen customer relationships.",
      techStack: ["React.js", "Tailwind CSS", "Node.js", "E-commerce Engine", "CRM Integration"],
      features: ["Large industrial product inventory", "Secure B2B ordering", "Customer dashboards", "Technical documentation", "Support & inquiry management"],
      impact: ["Simplified procurement workflows", "Improved operational efficiency", "Stronger B2B relationships", "Increased conversion rates"],
      img: "/media/portfolio-banners/bjerring-online.png",
      tags: ["Web", "B2B", "E-commerce"]
    },
    // {
    //   id: 10,
    //   title: "Unicorso",
    //   client: "Christopher Young, CTO at Dev Grid, US",
    //   duration: "1 Week",
    //   link: "#",
    //   description: "Unicorso is a scalable e-learning ecosystem offering courses, quizzes, and puzzles for individuals and businesses seeking upskilling solutions.",
    //   techStack: ["React.js", "Tailwind CSS", "Node.js", "LMS Platform", "Cloud Infrastructure"],
    //   features: ["Multi-domain learning content", "Courses, quizzes & puzzles", "Business training solutions", "Scalable architecture", "User-friendly interface"],
    //   impact: ["Increased learning engagement", "Flexible upskilling options", "Improved corporate training delivery", "Scalable digital education system"],
    //   img: "",
    //   tags: ["Web", "Education", "LMS"]
    // },
    {
      id: 11,
      slug: "phillips-live",
      title: "Phillips Live",
      client: "Daniel Garcia, CTO Web Wizards, USA",
      duration: "2 Weeks",
      link: "https://phillips.live/",
      description: "Phillips Live is a next-generation live streaming platform enabling creators to broadcast events, engage audiences in real time, and monetize content through advanced tools.",
      techStack: ["React.js", "Tailwind CSS", "Node.js", "WebRTC / Streaming APIs", "Cloud Media Services"],
      features: ["High-quality live streaming", "Real-time chat & interaction", "Event scheduling & notifications", "Creator monetization tools", "Scalable streaming infrastructure"],
      impact: ["Increased creator-audience engagement", "Reliable streaming performance", "New monetization opportunities", "Strong community building"],
      img: "/media/portfolio-banners/phillips-live.png",
      tags: ["Web", "Streaming", "Media"]
    }
  ];
